version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
	  - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:385501908346:secret:DockerPassword-k9qNRj --query SecretString --output text)
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  build:
    commands:
      - echo Building the Docker image...  
      - docker build -t $DOCKER_IMAGE_URL:IMAGE_TAG .
      - docker tag $DOCKER_IMAGE_URL:$IMAGE_TAG $DOCKER_USERNAME/$DOCKER_IMAGE_URL:$IMAGE_TAG      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_URL:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' "$DOCKER_IMAGE_URL" "$DOCKER_USERNAME/$DOCKER_IMAGE_URL:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json