version: 0.2

env:
  secrets-manager:
    DOCKER_PASSWORD: "DockerPassword:DOCKER_PASSWORD"

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo "Docker user name: $DOCKER_USERNAME"
      - echo "Docker password: $DOCKER_PASSWORD"
      - echo "Docker image name: $DOCKER_IMAGE_NAME"
      - echo "Docker image tag: $DOCKER_IMAGE_TAG"
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo Building the Docker image...  
      - docker build -t $DOCKER_IMAGE_NAME:DOCKER_IMAGE_TAG .
      - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG      
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' "$DOCKER_IMAGE_NAME" "$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json