version: 0.2

env:
  shell: bash
  secrets-manager:
    DOCKER_PASSWORD: "DockerCredentials:DockerPassword"
    
phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $DOCKER_USERNAME
      - echo "$DOCKER_USERNAME"
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build:
    commands:
      - echo Building the Docker image...  
      - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' "$DOCKER_IMAGE_NAME" "$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" > imagedefinitions.json
      
artifacts:
  files: imagedefinitions.json